// AUTO-GENERATED by scripts/update_dashboard_data.py -- 2026-02-23 21:15
// Source: scripts/leads-enriched-emails.csv (8360 leads)
// DO NOT EDIT MANUALLY

export interface DashboardStats {
  totalLeads: number;
  withEmail: number;
  withoutEmail: number;
  withPhone: number;
  withWebsite: number;
  highScore: number;
  mediumScore: number;
  lowScore: number;
  avgScore: number;
  avgRating: number;
  totalReviews: number;
  emailRate: number;
  phoneRate: number;
  websiteRate: number;
  byVerticale: Record<string, number>;
  byVille: Record<string, number>;
  bySource: Record<string, number>;
  byScore: { high: number; medium: number; low: number };
  lastUpdated: string;
}

export interface CategoryRate {
  name: string;
  total: number;
  withEmail: number;
  rate: number;
}

export interface CityRate {
  name: string;
  total: number;
  withEmail: number;
  rate: number;
}

export function getDashboardStats(): DashboardStats {
  return {
    totalLeads: 8360,
    withEmail: 14,
    withoutEmail: 8346,
    withPhone: 8015,
    withWebsite: 7415,
    highScore: 7009,
    mediumScore: 1351,
    lowScore: 0,
    avgScore: 85.6,
    avgRating: 4.6,
    totalReviews: 1616964,
    emailRate: 0.2,
    phoneRate: 95.9,
    websiteRate: 88.7,
    byVerticale: {
    "Centre de formation": 353,
    "Centre de formation continue": 316,
    "Dentiste": 287,
    "Auto-école": 273,
    "Expert-comptable": 255,
    "Kinésithérapeute": 254,
    "Salon de coiffure": 254,
    "Établissement d'enseignement supérieur": 251,
    "Agence immobilière": 248,
    "Plombier": 246,
    "Hôtel": 246,
    "Électricien": 239,
    "Institut de beauté": 238,
    "Agence de voyages": 238,
    "Crèche": 236,
    "Fleuriste": 229,
    "Ostéopathe": 216,
    "Coach particulier": 193,
    "Service de nettoyage et d'entretien": 192,
    "Photographe": 178,
  },
    byVille: {
    "Strasbourg": 549,
    "Lille": 529,
    "Bordeaux": 527,
    "Nice": 513,
    "Nantes": 510,
    "Reims": 507,
    "Rennes": 499,
    "Toulouse": 453,
    "Le Havre": 446,
    "Saint-Étienne": 445,
    "Grenoble": 443,
    "Toulon": 409,
    "Montpellier": 381,
    "Paris": 371,
    "Autre": 214,
  },
    bySource: {
      "Google Maps Scraping": 8360,
    },
    byScore: {
      high: 7009,
      medium: 1351,
      low: 0,
    },
    lastUpdated: "2026-02-23 21:15",
  };
}

export function getCategoryEmailRates(): CategoryRate[] {
  return [
    { name: "Centre de formation", total: 353, withEmail: 0, rate: 0.0 },
    { name: "Centre de formation continue", total: 316, withEmail: 1, rate: 0.3 },
    { name: "Dentiste", total: 287, withEmail: 0, rate: 0.0 },
    { name: "Auto-école", total: 273, withEmail: 0, rate: 0.0 },
    { name: "Expert-comptable", total: 255, withEmail: 0, rate: 0.0 },
    { name: "Kinésithérapeute", total: 254, withEmail: 0, rate: 0.0 },
    { name: "Salon de coiffure", total: 254, withEmail: 0, rate: 0.0 },
    { name: "Établissement d'enseignement supérieur", total: 251, withEmail: 4, rate: 1.6 },
    { name: "Agence immobilière", total: 248, withEmail: 0, rate: 0.0 },
    { name: "Plombier", total: 246, withEmail: 0, rate: 0.0 },
    { name: "Hôtel", total: 246, withEmail: 0, rate: 0.0 },
    { name: "Électricien", total: 239, withEmail: 0, rate: 0.0 },
    { name: "Institut de beauté", total: 238, withEmail: 0, rate: 0.0 },
    { name: "Agence de voyages", total: 238, withEmail: 0, rate: 0.0 },
    { name: "Crèche", total: 236, withEmail: 0, rate: 0.0 },
    { name: "Fleuriste", total: 229, withEmail: 0, rate: 0.0 },
    { name: "Ostéopathe", total: 216, withEmail: 0, rate: 0.0 },
    { name: "Coach particulier", total: 193, withEmail: 0, rate: 0.0 },
    { name: "Service de nettoyage et d'entretien", total: 192, withEmail: 0, rate: 0.0 },
    { name: "Photographe", total: 178, withEmail: 0, rate: 0.0 }
  ];
}

export function getCityEmailRates(): CityRate[] {
  return [
    { name: "Strasbourg", total: 549, withEmail: 0, rate: 0.0 },
    { name: "Lille", total: 529, withEmail: 0, rate: 0.0 },
    { name: "Bordeaux", total: 527, withEmail: 0, rate: 0.0 },
    { name: "Nice", total: 513, withEmail: 0, rate: 0.0 },
    { name: "Nantes", total: 510, withEmail: 1, rate: 0.2 },
    { name: "Reims", total: 507, withEmail: 0, rate: 0.0 },
    { name: "Rennes", total: 499, withEmail: 0, rate: 0.0 },
    { name: "Toulouse", total: 453, withEmail: 0, rate: 0.0 },
    { name: "Le Havre", total: 446, withEmail: 0, rate: 0.0 },
    { name: "Saint-Étienne", total: 445, withEmail: 0, rate: 0.0 },
    { name: "Grenoble", total: 443, withEmail: 0, rate: 0.0 },
    { name: "Toulon", total: 409, withEmail: 0, rate: 0.0 },
    { name: "Montpellier", total: 381, withEmail: 0, rate: 0.0 },
    { name: "Paris", total: 371, withEmail: 6, rate: 1.6 },
    { name: "Autre", total: 214, withEmail: 0, rate: 0.0 }
  ];
}

export interface ApifyRunStatus {
  runId: string;
  datasetId: string;
  status: string;
  queriesCount: number;
  verticale: string;
  resultsCount?: number;
}

export function getApifyRuns(): ApifyRunStatus[] {
  return [
    { runId: "WMS8gIAQ5rqzyghf0", datasetId: "1R95ndihhQhYmX7Pv", status: "SUCCEEDED", queriesCount: 30, verticale: "Formation Paris+Lyon", resultsCount: 447 },
    { runId: "JH3n4GsiBgmTidFfm", datasetId: "d75bTGRX0avyXyzJ8", status: "SUCCEEDED", queriesCount: 50, verticale: "Formation France Batch 1", resultsCount: 579 },
    { runId: "gLcR1g5PhdOFUwQRw", datasetId: "KVOtVsZexVIpJCvd7", status: "SUCCEEDED", queriesCount: 50, verticale: "Formation + Auto-ecole", resultsCount: 395 },
    { runId: "BwMU7MRjkqHZpNKL5", datasetId: "fBvNu8dFcJUjiwZAC", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 3", resultsCount: 947 },
    { runId: "XFD7PTtDDYQdWODxO", datasetId: "KFWY4BoPSH7GwZMig", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 4", resultsCount: 925 },
    { runId: "mOb8hvAId5vETHbYP", datasetId: "mKkV3YSzTfRSKPqWz", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 5", resultsCount: 912 },
    { runId: "EBJwkNWs9qnOnDr2H", datasetId: "SlXorLlzSLhf8CfcU", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 6", resultsCount: 921 },
    { runId: "VvsH1PuPTHa1vnIe7", datasetId: "6vTJdV8EPwbYz8qVR", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 7", resultsCount: 914 },
    { runId: "si1VpqXtNqdk1JK21", datasetId: "79cWMFzVOeYKTNj76", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 8", resultsCount: 855 },
    { runId: "UWkYvTtUA3E6OAJde", datasetId: "fB8yPUVaSzNYiw7XB", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 9", resultsCount: 870 },
    { runId: "bivuRtrsbFZhN2mDs", datasetId: "JHdQYQit3CPoZMfe1", status: "SUCCEEDED", queriesCount: 50, verticale: "Multi-verticale Chunk 10", resultsCount: 852 },
  ];
}

export interface PipelineStage {
  name: string;
  count: number;
  color: string;
}

export function getPipelineStages(): PipelineStage[] {
  return [
    { name: "Scrappe", count: 8360, color: "#6366f1" },
    { name: "Email Trouve", count: 14, color: "#8b5cf6" },
    { name: "Pret Campagne", count: 14, color: "#22c55e" },
    { name: "Contacte", count: 0, color: "#f59e0b" },
    { name: "Repondu", count: 0, color: "#06b6d4" },
    { name: "RDV Booke", count: 0, color: "#10b981" },
  ];
}

export interface EnrichmentSummary {
  method: string;
  cost: string;
  successRate: number;
  totalEmailsFound: number;
  totalLeadsProcessed: number;
  timestamp: string;
}

export function getEnrichmentSummary(): EnrichmentSummary {
  return {
    method: "Website scraping (aiohttp + BeautifulSoup)",
    cost: "0 EUR",
    successRate: 0.2,
    totalEmailsFound: 14,
    totalLeadsProcessed: 8360,
    timestamp: "2026-02-23 21:15",
  };
}
